### PR TITLE
Fix death message false positives

### PR DESCRIPTION
**Pull request by MageLuingil**
This fixes issue #70 by replacing the death keyword config option with a death message regex config option.

### CODE REVIEW

**Comment by destruc7i0n** [comment]
Nice work! Thanks for the report and fix.

Seeing as this is removing an option for the config, do you think you could add a message somewhere (maybe `loadConfig` in `Shulker.ts`) alerting those who may have the old config line that they need to update their config to correctly support this? Not sure myself about how many actively upgrade the bot, but would help those who do.

**Comment by MageLuingil** [comment]
That sounds like a really good idea. I presume you're thinking just a warning to the console? I haven't tested with that option still present (and I'm still new to typescript) so I don't know if unexpected config options will throw errors.

In any case, I'll look into adding that when I have some time later.

**Comment by destruc7i0n** [comment]
Yeah just a warning for now. I should add some better config handling, to automatically add defaults for changes like these...

**Comment by MageLuingil** [comment]
Okay, I added a configurable array for config option deprecation notices. Not sure if my way is the "best" way to do it in typescript, but there's at least a deprecation notice now, pointing people to the README.

Further feedback is of course welcome!

**Comment by MageLuingil** [comment]
On a side note, my death message regex is based off of information from the Minecraft wiki (which has on occasion been wrong). Comparing my list to yours, it looks like I'm missing the keywords "finished", "speared", and "removed".  I see "finished" in the list of removed death messages on the wiki (it appears it should have been handled by other keywords anyway), but I don't see any references to the other two.

Do you happen to know what the death messages for "speared" and "removed" were, and if I need to add them to my regex?

**Comment by destruc7i0n** [comment]
The best place to reference the death messages would be the language files. I attached a trimmed version of the latest `en_us` one for reference.

I do not see them either, not sure exactly where they came from. 

@TheZackCodec had made the original PR for that, do you happen to know what those are form? 

[en_us.txt](https://github.com/destruc7i0n/shulker/files/6502869/en_us.txt)

**Comment by MageLuingil** [comment]
Thanks for pointing out the language files to me! I don't know why I didn't think to use those from the start.

So, I may have slightly overkilled this, but I compiled a list of all death messages from the EN language files for all versions 1.12 - 1.16.5. The only message I was missing previously was an old typo in 1.12 for "[player] discovered floor was lava" (missing the "the").

I honestly don't know if this project works correctly with log files from 1.12, but I'll probably add support for that death message to my regex anyway. As for those other two messages, if they were ever in the game, it was probably only in snapshots.

**Comment by destruc7i0n** [comment]
The project came out in 2016 when 1.8.9 had released. I think that 1.12 is a good lower bound, however.

**Comment by destruc7i0n** [comment]
@MageLuingil Hey! Just wanted to check if you had a chance to update your regex as you mentioned above. (GitHub removes from homepage after 14 days so just wanted to keep this fresh on the page)

**Comment by MageLuingil** [comment]
Sorry for the delay; I added that missed death message.

I'm going to work on the death messages from 1.7-1.12 as well, but it may take a little longer.

**Comment by destruc7i0n** [comment]
I've gone ahead and merged this, had another report which brought this to my attention again. Thanks again for the contribution! If you wish to update the death messages at another, feel free to make another PR

**Comment by MageLuingil** [comment]
So I (finally) made a script that compiles a list of all death messages across all release versions of the game, and checked that list against the regex currently being used. As of 1.18.1, we're catching all death messages (except for an unused one from 1.5 that later got removed). That means no more death message updates coming from me for now!

It also means future changes *should* be easier to find using this script (which I have [here](https://gist.github.com/MageLuingil/4728c190efebdde4718757a60d7679a1) if you're interested).

**Pull request merged**
